### ISSUE TITLE
esthri-cli isnt published on crates.io

### ISSUE THREAD

**Issue by jayvdb** [swift-nav/esthri#277]

**Comment by jeffbski-sketch** [comment]
Makes it much easier to install without downloading the git repo

**Comment by jayvdb** [comment]
Yes, it will mean it can be installed using https://crates.io/crates/cargo-quickinstall or https://crates.io/crates/cargo-binstall for very quick prebuilt binary installs, perfect for CI.

**Comment by john-michaelburke** [comment]
https://crates.io/crates/esthri-cli
